### ISSUE TITLE
File extension collision:  cls maps to languages 'Visual Basic' and 'Apex Class'

### ISSUE THREAD

**Issue by RedaBenh** [couchand/cloc-force#1]
Hi,
I get this error when i run cloc command with force-def.txt .

```
cloc --read-lang-def=force-def.txt  classes                              
File extension collision:  cls maps to languages 'Visual Basic' and 'Apex Class'
Edit force-def.txt and remove cls from one of these two language definitions.

```

Can you please tell me how can i fix this  ?

**Comment by couchand** [comment]
It looks like you're loading another config file that defines a `.cls` file as being Visual Basic code.  Since that extension conflicts with the one for Apex classes, you'll need to choose which one to use when running `cloc` against a particular project.

One way to do that would be with either of the `--force-lang` or `--force-lang-def` options, such as:

``` sh
> cloc --force-lang-def=force-def.txt classes
```

For more information, try `cloc --help`.
